---
title: "Data_Products"
author: "Benedetto Lo Cicero"
date: "16 Juli 2019"
output: slidy_presentation
---

## Basic economic datas

In this html document I want to show some economic facts of 2016 obtained from the economic freedom institute (https://www.fraserinstitute.org/).
First of all I load the dataset and I will clean it

```{r message=FALSE, warning=TRUE}
df <- read.csv2("./2018_EconomicFreedom.csv")
df <- df[,1:9]
df <- df[df$Year==2016,]
library(stringr)
library(janitor)
colnames(df) <- str_remove_all(colnames(df),'X[:digit:][:punct:]{2}')
colnames(df) <- str_replace_all(colnames(df),'[:punct:]'," ")
colnames(df) <- str_replace_all(colnames(df),'   ',' and ')
colnames(df) <- gsub('\\s+', '', colnames(df))
df <- remove_empty(df, which = c("rows", "cols"))
df$ISOCode <- df$ISOCode %>% as.factor()
df$Countries <- df$Countries %>% as.factor()
df$hover <- with(df, paste( "Size of Government ", SizeofGovernment , "<br>",
                           "Legal System and Property Rights", LegalSystemandPropertyRights , "<br>", 
                           "Sound Money", SoundMoney  , "<br>",
                           "Freedomto trade internationally", Freedomtotradeinternationally  , "<br>",
                           "Regulation", Regulation  , "<br>"))
```

## Basic economic plot with plotly

I colour the country using their summary index as reference, and hoovering on the countries give more insights.

```{r echo=FALSE, message=FALSE, warning=FALSE}
# specify some map projection/options


library(plotly)
p <- plot_geo(df, locationmode = 'world') %>% 
  add_trace(
    z = ~SUMMARYINDEX, text = ~hover, locations = ~ISOCode,
    color = ~SUMMARYINDEX, colors = c("green","blue") 
  ) %>%
  colorbar(title = "Summary Index")

p

```
